<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GM.Scheduling" Version="1.0.0" />
        <PackageReference Include="GM.Scheduling.EntityFramework" Version="1.0.0" />
        <PackageReference Include="GM.DistributedLock" Version="1.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    </ItemGroup>

</Project>
